import { z } from "zod";
import { listQueryBase } from "./list.js";
import { optionalText } from "./orders.js";
import { calendarDate, machineTypesForStage, type MachineType } from "./production.js";

/**
 * Shift planning and daily tickets — docs/shift-planning-plan.md (v2).
 *
 * The plant runs three eight-hour shifts. The week is Sunday to Saturday and
 * opens with SUNDAY NIGHT (22:00) and closes with SATURDAY AFTERNOON: 18
 * fixed day-shifts, generated by construction when a week is opened. A
 * person is on ONE shift type for the WHOLE week; which days that covers is
 * derived from the type (`daysForShiftType`), never stored.
 *
 * Shift hours are a plant fact and live here, not in a table: a fourth shift
 * type is a migration plus an edit to `SHIFT_HOURS`, which is the right cost
 * for something that changes once a decade. Both sides read the same
 * constants, so the planner and the server's stored bounds agree.
 */

export const SHIFT_TYPES = ["NIGHT", "MORNING", "AFTERNOON"] as const;
export type ShiftType = (typeof SHIFT_TYPES)[number];

/** Wall-clock hours in plant time. `endsNextDay` is the night shift only. */
export const SHIFT_HOURS: Record<ShiftType, { start: number; end: number; endsNextDay: boolean }> = {
  NIGHT: { start: 22, end: 6, endsNextDay: true },
  MORNING: { start: 6, end: 14, endsNextDay: false },
  AFTERNOON: { start: 14, end: 22, endsNextDay: false },
};

export const SHIFT_LENGTH_MS = 8 * 60 * 60 * 1000;

/**
 * Africa/Tunis is a fixed +01:00: Tunisia has had no daylight saving since
 * 2009. One named constant rather than an `Intl` time-zone lookup, so the
 * shift bounds can be built as plain ISO strings on both sides. If DST ever
 * returns this becomes an `Intl` computation and the stored `startsAt` rows
 * across the switch need a backfill — see the plan's risks.
 */
export const PLANT_UTC_OFFSET = "+01:00";
export const PLANT_UTC_OFFSET_MS = 60 * 60 * 1000;

export const SHIFT_WEEK_STATUSES = ["DRAFT", "PUBLISHED"] as const;
export type ShiftWeekStatus = (typeof SHIFT_WEEK_STATUSES)[number];

export const SHIFT_CHANGE_KINDS = ["MOVE", "SWAP", "REPLACE", "REMOVE", "ADD"] as const;
export type ShiftChangeKind = (typeof SHIFT_CHANGE_KINDS)[number];

/** The two kinds a worker may request on their own row. */
export const WORKER_CHANGE_KINDS = ["MOVE", "SWAP"] as const;
export type WorkerChangeKind = (typeof WORKER_CHANGE_KINDS)[number];

export const SHIFT_CHANGE_STATUSES = ["PENDING", "ACCEPTED", "REJECTED", "WITHDRAWN"] as const;
export type ShiftChangeStatus = (typeof SHIFT_CHANGE_STATUSES)[number];

export const SHIFT_TASK_TYPES = ["SETTING", "PRODUCTION", "PRINTING", "CLEANING"] as const;
export type ShiftTaskType = (typeof SHIFT_TASK_TYPES)[number];

export const SHIFT_TASK_STATUSES = ["OPEN", "DONE"] as const;
export type ShiftTaskStatus = (typeof SHIFT_TASK_STATUSES)[number];

export interface WeekShift {
  /** 0 = the Sunday the week starts on, 6 = Saturday. */
  dayOffset: number;
  type: ShiftType;
}

/**
 * The 18 day-shifts of a week in chronological order: Sunday night; Monday
 * to Friday morning, afternoon, night; Saturday morning and afternoon. This
 * list is what `openWeek` creates and what the day view draws, so the two
 * cannot disagree about which slots exist.
 */
export const WEEK_SHIFTS: readonly WeekShift[] = [
  { dayOffset: 0, type: "NIGHT" },
  ...[1, 2, 3, 4, 5].flatMap((dayOffset) =>
    (["MORNING", "AFTERNOON", "NIGHT"] as const).map((type) => ({ dayOffset, type })),
  ),
  { dayOffset: 6, type: "MORNING" },
  { dayOffset: 6, type: "AFTERNOON" },
];

export function shiftExists(dayOffset: number, type: ShiftType): boolean {
  return WEEK_SHIFTS.some((s) => s.dayOffset === dayOffset && s.type === type);
}

/**
 * The days (0 = Sunday … 6 = Saturday) a person on `type` works this week:
 * Sunday to Friday nights, or Monday to Saturday mornings / afternoons.
 * Derived from `WEEK_SHIFTS`, so the roster and the generated day-shifts
 * cannot disagree.
 */
export function daysForShiftType(type: ShiftType): number[] {
  return WEEK_SHIFTS.filter((s) => s.type === type).map((s) => s.dayOffset);
}

/** Parses a YYYY-MM-DD as UTC midnight — how every `@db.Date` column is written. */
export function utcDay(isoDay: string): Date {
  return new Date(`${isoDay}T00:00:00.000Z`);
}

/** The YYYY-MM-DD of a UTC-midnight Date, or of an ISO string carrying one. */
export function isoDayOf(value: string | Date): string {
  return (typeof value === "string" ? value : value.toISOString()).slice(0, 10);
}

export function addDays(isoDay: string, days: number): string {
  const date = utcDay(isoDay);
  date.setUTCDate(date.getUTCDate() + days);
  return date.toISOString().slice(0, 10);
}

/** 0 = Sunday … 6 = Saturday, for a YYYY-MM-DD. */
export function weekdayOf(isoDay: string): number {
  return utcDay(isoDay).getUTCDay();
}

export function isSunday(isoDay: string): boolean {
  return weekdayOf(isoDay) === 0;
}

/** The Sunday on or before `isoDay`: the `weekStart` of the week it falls in. */
export function weekStartOf(isoDay: string): string {
  return addDays(isoDay, -weekdayOf(isoDay));
}

/** Today's date in plant time, as YYYY-MM-DD. */
export function plantDay(now: Date = new Date()): string {
  return new Date(now.getTime() + PLANT_UTC_OFFSET_MS).toISOString().slice(0, 10);
}

/**
 * The absolute instants a shift runs between, from its start date and type.
 * Built as ISO strings with the plant offset rather than through `Intl`, so
 * the same eight hours come out on the server and in the browser whatever
 * zone the machine is in.
 */
export function shiftBounds(isoDay: string, type: ShiftType): { startsAt: Date; endsAt: Date } {
  const hour = String(SHIFT_HOURS[type].start).padStart(2, "0");
  const startsAt = new Date(`${isoDay}T${hour}:00:00${PLANT_UTC_OFFSET}`);
  return { startsAt, endsAt: new Date(startsAt.getTime() + SHIFT_LENGTH_MS) };
}

/** When the week's last shift (Saturday afternoon) ends. */
export function weekEndsAt(weekStart: string): Date {
  return shiftBounds(addDays(weekStart, 6), "AFTERNOON").endsAt;
}

/**
 * Which machines a ticket of this type may name: printing tickets the
 * presses, production tickets the bag machines, and null for setting and
 * cleaning, which may name any active machine. Reuses the production module's
 * stage mapping so the two never disagree about what a press is.
 */
export function taskMachineTypes(type: ShiftTaskType): readonly MachineType[] | null {
  if (type === "PRINTING") return machineTypesForStage("PRINTING");
  if (type === "PRODUCTION") return machineTypesForStage("PRODUCER");
  return null;
}

/**
 * "Missed" is derived, never stored: an open ticket on a shift that has ended.
 * One rule for the card's pill and for any server-side reading of it.
 */
export function isTaskMissed(
  task: { status: ShiftTaskStatus },
  shift: { endsAt: string | Date },
  now: Date = new Date(),
): boolean {
  return task.status === "OPEN" && new Date(shift.endsAt).getTime() < now.getTime();
}

/**
 * How long after a shift ends a worker may still mark its tickets done: long
 * enough to close the sheet at handover, short enough that a miss is not
 * erased the next day. The admin is unbounded. Two hours is an assumption
 * recorded in the plan's risks.
 */
export const TASK_DONE_GRACE_MS = 2 * 60 * 60 * 1000;

/**
 * A worker's window for marking a ticket done: from the shift's start (the
 * work has to have happened) until the grace after its end. The admin is
 * unbounded both ways.
 */
export function canWorkerMarkDone(
  shift: { startsAt: string | Date; endsAt: string | Date },
  now: Date = new Date(),
): boolean {
  const t = now.getTime();
  return (
    t >= new Date(shift.startsAt).getTime() &&
    t < new Date(shift.endsAt).getTime() + TASK_DONE_GRACE_MS
  );
}

/** A Sunday, as YYYY-MM-DD: the only date a week can start on. */
const sunday = calendarDate.refine(isSunday, "A week starts on a Sunday");

const id = z.string().min(1);
const shiftType = z.enum(SHIFT_TYPES);

const clearableText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .nullish()
    .transform((value) => (value === null ? null : value || undefined));

export const weekStartInput = z.object({ weekStart: sunday });
export const weekIdInput = z.object({ weekId: id });
export const shiftIdInput = z.object({ shiftId: id });
export const assignmentIdInput = z.object({ assignmentId: id });
export const changeIdInput = z.object({ changeId: id });
export const taskIdInput = z.object({ id });
export const dayInput = z.object({ date: calendarDate });

export const copyWeekInput = z.object({ weekId: id, fromWeekId: id });

/** Moves someone to another shift on a DRAFT week; a published one goes through `adminChangeInput`. */
export const moveDraftInput = z.object({ assignmentId: id, type: shiftType });

/** 60 is above the whole roster (39 today); a picker cannot send more. */
const employeeIds = z.array(id).min(1, "Pick at least one person").max(60);

/**
 * Puts people on one shift type for the whole week. With `moveIfPlaced`,
 * someone already on another shift is moved rather than reported back — the
 * add modal's "everyone" scope.
 */
export const assignWeekInput = z.object({
  weekId: id,
  type: shiftType,
  employeeIds,
  moveIfPlaced: z.boolean().default(false),
});

/**
 * An admin's change on a published week, for the rest of the week. The
 * person's current shift is never sent: the service reads it from their row
 * and records it as `fromType`. What each kind needs beyond the person:
 *
 *   MOVE     toType
 *   SWAP     counterpart (whose shift becomes `toType`)
 *   REPLACE  counterpart (who takes the person's shift)
 *   REMOVE   nothing
 *   ADD      toType
 */
export const adminChangeInput = z
  .object({
    weekId: id,
    kind: z.enum(SHIFT_CHANGE_KINDS),
    employeeId: id,
    toType: shiftType.optional(),
    counterpartEmployeeId: id.optional(),
    reason: optionalText(500),
  })
  .superRefine((value, ctx) => {
    const needsTo = value.kind === "MOVE" || value.kind === "ADD";
    const needsCounterpart = value.kind === "SWAP" || value.kind === "REPLACE";
    if (needsTo && !value.toType) {
      ctx.addIssue({ code: "custom", path: ["toType"], message: "Pick the shift to move to" });
    }
    if (needsCounterpart && !value.counterpartEmployeeId) {
      ctx.addIssue({
        code: "custom",
        path: ["counterpartEmployeeId"],
        message: "Pick the other person",
      });
    }
    if (value.counterpartEmployeeId && value.counterpartEmployeeId === value.employeeId) {
      ctx.addIssue({
        code: "custom",
        path: ["counterpartEmployeeId"],
        message: "The other person must be someone else",
      });
    }
  });

/**
 * A worker's request on their own row, for the rest of the week: move to
 * another shift, or swap with someone on another shift. The reason is
 * required: the admin decides from the inbox without a conversation.
 */
export const requestChangeInput = z
  .object({
    weekId: id,
    kind: z.enum(WORKER_CHANGE_KINDS),
    toType: shiftType.optional(),
    counterpartEmployeeId: id.optional(),
    reason: z.string().trim().min(1, "Say why").max(500),
  })
  .superRefine((value, ctx) => {
    if (value.kind === "MOVE" && !value.toType) {
      ctx.addIssue({ code: "custom", path: ["toType"], message: "Pick the shift to move to" });
    }
    if (value.kind === "SWAP" && !value.counterpartEmployeeId) {
      ctx.addIssue({
        code: "custom",
        path: ["counterpartEmployeeId"],
        message: "Pick who you would swap with",
      });
    }
  });

export const rejectChangeInput = z.object({
  changeId: id,
  reason: optionalText(500),
});

export const SHIFT_CHANGE_SORT_KEYS = ["createdAt", "decidedAt"] as const;
export type ShiftChangeSortKey = (typeof SHIFT_CHANGE_SORT_KEYS)[number];

export const SHIFT_CHANGE_FACET_KEYS = ["pending", "accepted", "rejected", "withdrawn"] as const;
export type ShiftChangeFacet = (typeof SHIFT_CHANGE_FACET_KEYS)[number];

export const listShiftChangesInput = listQueryBase.extend({
  sortBy: z.enum(SHIFT_CHANGE_SORT_KEYS).default("createdAt"),
  filter: z.enum(["all", ...SHIFT_CHANGE_FACET_KEYS]).default("pending"),
});

/** One person, one day-shift, one task. The machine is optional. */
export const createShiftTaskInput = z.object({
  shiftId: id,
  employeeId: id,
  type: z.enum(SHIFT_TASK_TYPES),
  machineId: id.optional(),
  orderId: id.optional(),
  note: optionalText(2000),
});

/**
 * `machineId` and `orderId` are three-valued on update, like the employee
 * form's optional text: undefined leaves it, null clears it, a string sets it.
 */
export const updateShiftTaskInput = z.object({
  id,
  employeeId: id,
  type: z.enum(SHIFT_TASK_TYPES),
  machineId: id.nullish(),
  orderId: id.nullish(),
  note: clearableText(2000),
});

export const setTaskDoneInput = z.object({
  id,
  done: z.boolean(),
});

export const myWeekInput = z.object({
  weekStart: sunday.optional(),
});

export type WeekStartInput = z.infer<typeof weekStartInput>;
export type WeekIdInput = z.infer<typeof weekIdInput>;
export type ShiftIdInput = z.infer<typeof shiftIdInput>;
export type AssignmentIdInput = z.infer<typeof assignmentIdInput>;
export type ChangeIdInput = z.infer<typeof changeIdInput>;
export type TaskIdInput = z.infer<typeof taskIdInput>;
export type DayInput = z.infer<typeof dayInput>;
export type CopyWeekInput = z.infer<typeof copyWeekInput>;
export type AssignWeekInput = z.infer<typeof assignWeekInput>;
export type MoveDraftInput = z.infer<typeof moveDraftInput>;
export type AdminChangeInput = z.infer<typeof adminChangeInput>;
export type RequestChangeInput = z.infer<typeof requestChangeInput>;
export type RejectChangeInput = z.infer<typeof rejectChangeInput>;
export type ListShiftChangesInput = z.infer<typeof listShiftChangesInput>;
export type CreateShiftTaskInput = z.infer<typeof createShiftTaskInput>;
export type UpdateShiftTaskInput = z.infer<typeof updateShiftTaskInput>;
export type SetTaskDoneInput = z.infer<typeof setTaskDoneInput>;
export type MyWeekInput = z.infer<typeof myWeekInput>;
